import eslintPluginReact from 'eslint-plugin-react';
import eslintPluginReactHooks from 'eslint-plugin-react-hooks';
import simpleImportSort from 'eslint-plugin-simple-import-sort';
import tseslint from 'typescript-eslint';
import xoTypescript from 'eslint-config-xo-typescript';

export default tseslint.config(
  {
    ignores: ['node_modules/', 'dist/', '.expo/', 'android/', 'ios/', '**/*.json', 'eslint.config.mjs', 'metro.config.js', 'babel.config.js', 'app.config.js'],
  },
  ...xoTypescript,
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      react: eslintPluginReact,
      'react-hooks': eslintPluginReactHooks,
      'simple-import-sort': simpleImportSort,
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      ...eslintPluginReact.configs.recommended.rules,
      ...eslintPluginReactHooks.configs.recommended.rules,

      // XO style overrides to match previous config behavior
      'no-console': 'off',
      'no-param-reassign': 'off',
      'prefer-const': 'off',
      'func-names': 'off',
      'max-classes-per-file': 'off',
      radix: 'off',
      'consistent-return': 'off',
      'class-methods-use-this': 'off',

      // TypeScript rules
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/no-shadow': 'off',

      // React rules
      'react/function-component-definition': 'off',
      'react/prop-types': 'off',
      'react/no-array-index-key': 'off',
      'react/jsx-curly-brace-presence': 'off',
      'react/require-default-props': 'off',
      'react/no-unstable-nested-components': 'off',
      'react/jsx-no-useless-fragment': 'off',
      'react-hooks/exhaustive-deps': 'off',

      // Stylistic rules to match existing code style
      '@stylistic/indent': ['error', 2],
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/semi': ['error', 'always'],
      '@stylistic/arrow-parens': ['error', 'always'],
      '@stylistic/comma-dangle': ['error', 'only-multiline'],
      '@stylistic/padding-line-between-statements': 'off',
      'capitalized-comments': 'off',
      curly: 'off',
      'no-negated-condition': 'off',
      'no-warning-comments': 'off',
      'logical-assignment-operators': 'off',
      '@typescript-eslint/naming-convention': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/consistent-type-imports': 'off',
      '@typescript-eslint/consistent-type-definitions': 'off',
      '@typescript-eslint/consistent-indexed-object-style': 'off',
      '@typescript-eslint/consistent-type-assertions': 'off',
      '@typescript-eslint/promise-function-async': 'off',
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-restricted-types': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/member-ordering': 'off',
      '@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/no-inferrable-types': 'off',
      'object-shorthand': 'off',
      'unicorn/no-useless-undefined': 'off',
      'unicorn/prevent-abbreviations': 'off',
      'unicorn/no-null': 'off',
      'unicorn/prefer-module': 'off',
      'unicorn/filename-case': 'off',
      'unicorn/prefer-ternary': 'off',
      'unicorn/no-await-expression-member': 'off',
      'unicorn/switch-case-braces': 'off',
      'unicorn/no-nested-ternary': 'off',
      'unicorn/prefer-spread': 'off',
      'unicorn/prefer-string-replace-all': 'off',
      'unicorn/no-array-reduce': 'off',
      'unicorn/prefer-top-level-await': 'off',
      'unicorn/no-array-callback-reference': 'off',
      'unicorn/prefer-regexp-test': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'unicorn/prefer-array-flat-map': 'off',
      'unicorn/prefer-array-some': 'off',
      'unicorn/prefer-export-from': 'off',
      'unicorn/no-abusive-eslint-disable': 'off',
      'unicorn/import-style': 'off',
      'new-cap': 'off',
      '@typescript-eslint/class-literal-property-style': 'off',
      '@typescript-eslint/unified-signatures': 'off',
      '@stylistic/operator-linebreak': 'off',
      '@stylistic/function-paren-newline': 'off',
      'no-return-await': 'off',
      '@typescript-eslint/no-deprecated': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react/display-name': 'off',
      'no-eq-null': 'off',
      eqeqeq: 'off',
      'react-hooks/static-components': 'off',
      'react-hooks/refs': 'off',
      '@typescript-eslint/no-unsafe-enum-comparison': 'off',
      '@stylistic/max-len': 'off',
      '@stylistic/no-mixed-spaces-and-tabs': 'off',
      '@typescript-eslint/prefer-optional-chain': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react/no-unescaped-entities': 'off',
      'max-params': 'off',
      '@typescript-eslint/no-extraneous-class': 'off',
      '@typescript-eslint/restrict-plus-operands': 'off',
      '@stylistic/no-mixed-operators': 'off',
      'no-useless-escape': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      '@typescript-eslint/no-dynamic-delete': 'off',
      '@stylistic/max-statements-per-line': 'off',
      '@stylistic/multiline-ternary': 'off',

      // Import sorting
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
    },
  },
  {
    files: ['**/*.{js,jsx}'],
    plugins: {
      react: eslintPluginReact,
      'react-hooks': eslintPluginReactHooks,
      'simple-import-sort': simpleImportSort,
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
    rules: {
      ...eslintPluginReact.configs.recommended.rules,
      ...eslintPluginReactHooks.configs.recommended.rules,
      '@stylistic/indent': ['error', 2],
      '@stylistic/object-curly-spacing': ['error', 'always'],
      '@stylistic/arrow-parens': ['error', 'always'],
      '@stylistic/object-curly-newline': 'off',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'off',
      '@typescript-eslint/prefer-nullish-coalescing': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      'prefer-const': 'off',
      'unicorn/prefer-module': 'off',
      'unicorn/filename-case': 'off',
      '@typescript-eslint/naming-convention': 'off',
      'capitalized-comments': 'off',

      // Import sorting
      'simple-import-sort/imports': 'error',
      'simple-import-sort/exports': 'error',
    },
  }
);
