name: Prettier

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - ci/custom-gh-action

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Installing Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      # github actions env sucks
      - name: Install dependencies
        run: |
          bun install --dev
      - name: Prettier Action
        uses: Damego/prettier_action@5.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_plugins: '@trivago/prettier-plugin-sort-imports'
          prettier_options: --write **/*.{js,jsx,ts,tsx,md}
          commit_message: 'ci: prettified code'
