name: Prettier

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - development

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: git remote remove origin
      - run: git remote add origin ${{ github.event.pull_request.head.repo.clone_url }}
      - run: git fetch origin
      - run: git switch ${{ github.event.pull_request.head.ref }}
      - run: |
          gh api --method POST \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/$OWNER/$REPO/actions/runs/$RUN_ID/approve
        env:
          RUN_ID: ${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: github.event.pull_request.head.repo.owner
          REPO: github.event.pull_request.head.repo.name
      
      # - name: Installing Bun
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: latest
      # # github actions env sucks
      # - name: Install dependencies
      #   run: |
      #     bun install --dev
      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          #prettier_plugins: '@trivago/prettier-plugin-sort-imports'
          prettier_options: --write **/*.{js,jsx,ts,tsx,md}
          commit_message: 'ci: prettified code'
