name: Prettier

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - development

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - run: |
      #     git fetch ${{ github.event.pull_request.head.repo.clone_url }}
      # - run: |
      #     git switch ${{ github.event.pull_request.head.ref }}
      
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}
      #   with:
      #     ref: ${{ github.event.pull_request.head }}
      # # - run: |
      # #     git fetch ${{ github.event.pull_request.head.ref }}
      # 
      # - name: Installing Bun
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: latest
      # # github actions env sucks
      # - name: Install dependencies
      #   run: |
      #     bun install --dev
      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          #prettier_plugins: '@trivago/prettier-plugin-sort-imports'
          prettier_options: --write **/*.{js,jsx,ts,tsx,md}
          commit_message: 'ci: prettified code'
